# THIS IS EXPERIMENTAL
# the config file schema may change at any time

style:
  tag:
    color: cyan
    width_percentage: 25
    min_width: 20
  comment:
    color: blue
    width_percentage: 75
    min_width: 45
  snippet:
    color: white

finder:
  command: fzf
  overrides: --with-nth 1,2

cheats:
  paths:
    - $HOME/dotfiles/navi/cheats/luca # on unix-like os

shell:
  command: fish
